Change cask install to hyper (#809)
It looks like the cask package name has changed in the renaming

```
brew cask install hyperterm
Error: No available Cask for hyperterm
Error: nothing to install
```